apiVersion: v1
kind: Pod
metadata:
  name: orion
  labels:
    app: orion
spec:
  containers:
  - name: orion
    image: fiware/orion:3.11.0
    args: ["-dbhost", "mongo-service", "-corsOrigin", "__ALL", "-corsMaxAge", "600"]
    ports:
    - containerPort: 1026
