apiVersion: v1
kind: Pod
metadata:
  name: mongo-db
  labels:
    app: mongo
spec:
  containers:
  - name: mongo
    image: mongo:4.4
    args: ["--nojournal"]
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: mongo-data
      mountPath: /data/db
  volumes:
  - name: mongo-data
    persistentVolumeClaim:
      claimName: mongo-pvc
